# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < https://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < https://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < https://docs.platformio.org/page/userguide/cmd_ci.html >
#
#

language: python
python:
  - "3.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
  directories:
    - "~/.platformio"
    - $HOME/.cache/pip

env:
  - PLATFORMIO_CI_SRC=src/main.cpp PLATFORMIO_LIB_EXTRA_DIRS=/tmp/arduino-lib-master

install:
  - pip install -U platformio pip setuptools
  - platformio update

  - wget https://github.com/collab-project/arduino-lib/archive/master.zip -O /tmp/arduino-lib.zip
  - unzip /tmp/arduino-lib.zip -d /tmp

script:
  - platformio ci --project-conf platformio.ini --lib="."
